/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vevhdlemterygkpqusfq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldmhkbGVtdGVyeWdrcHF1c2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzMTM4ODgsImV4cCI6MjA4Nzg4OTg4OH0.Hvu1VyeSY2rbf0ni8C5-GyMSsqV7O0F0yPP-bLPtmLs"